package com.si_worklog.com;

import android.app.Activity;
import android.content.Context;
import android.os.Bundle;
import android.os.CancellationSignal;
import android.os.ParcelFileDescriptor;
import android.print.PageRange;
import android.print.PrintAttributes;
import android.print.PrintDocumentAdapter;
import android.print.PrintDocumentInfo;
import android.print.PrintManager;
import android.util.Base64;

import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

import java.io.FileOutputStream;
import java.io.OutputStream;

/**
 * Local Capacitor plugin: opens Android's system print dialog (PrintManager)
 * for a PDF generated by the web layer.
 *
 * The web app renders the exact A4 form layout to a PDF (jsPDF), passes it
 * here as base64, and the OS print dialog lets the user pick any installed
 * print service (a network/Bluetooth printer, "Save as PDF", Cloud Print
 * replacements, etc.).
 */
@CapacitorPlugin(name = "NativePrint")
public class NativePrintPlugin extends Plugin {

    @PluginMethod
    public void print(PluginCall call) {
        String base64 = call.getString("base64");
        String jobName = call.getString("jobName", "Document");
        if (base64 == null || base64.isEmpty()) {
            call.reject("Missing PDF data");
            return;
        }

        final byte[] pdfBytes;
        try {
            pdfBytes = Base64.decode(base64, Base64.DEFAULT);
        } catch (IllegalArgumentException e) {
            call.reject("Invalid PDF data");
            return;
        }

        final Activity activity = getActivity();
        if (activity == null) {
            call.reject("No activity available");
            return;
        }

        final String name = jobName != null ? jobName : "Document";

        activity.runOnUiThread(() -> {
            try {
                Context context = getContext();
                PrintManager printManager =
                        (PrintManager) context.getSystemService(Context.PRINT_SERVICE);
                if (printManager == null) {
                    call.reject("Print service unavailable");
                    return;
                }

                PrintAttributes attributes = new PrintAttributes.Builder()
                        .setMediaSize(PrintAttributes.MediaSize.ISO_A4)
                        .setColorMode(PrintAttributes.COLOR_MODE_COLOR)
                        .build();

                printManager.print(name, new PdfPrintAdapter(pdfBytes, name), attributes);
                call.resolve();
            } catch (Exception e) {
                call.reject("Print failed: " + e.getMessage());
            }
        });
    }

    /**
     * Streams the already-rendered PDF bytes into Android's print framework.
     * All pages are written as-is; the PDF is exactly A4 so the dialog preview
     * matches the paper.
     */
    private static class PdfPrintAdapter extends PrintDocumentAdapter {
        private final byte[] pdfBytes;
        private final String jobName;

        PdfPrintAdapter(byte[] pdfBytes, String jobName) {
            this.pdfBytes = pdfBytes;
            this.jobName = jobName;
        }

        @Override
        public void onLayout(
                PrintAttributes oldAttributes,
                PrintAttributes newAttributes,
                CancellationSignal cancellationSignal,
                LayoutResultCallback callback,
                Bundle extras) {
            if (cancellationSignal.isCanceled()) {
                callback.onLayoutCancelled();
                return;
            }
            PrintDocumentInfo info = new PrintDocumentInfo.Builder(jobName + ".pdf")
                    .setContentType(PrintDocumentInfo.CONTENT_TYPE_DOCUMENT)
                    .setPageCount(PrintDocumentInfo.PAGE_COUNT_UNKNOWN)
                    .build();
            callback.onLayoutFinished(info, true);
        }

        @Override
        public void onWrite(
                PageRange[] pages,
                ParcelFileDescriptor destination,
                CancellationSignal cancellationSignal,
                WriteResultCallback callback) {
            OutputStream out = null;
            try {
                out = new FileOutputStream(destination.getFileDescriptor());
                out.write(pdfBytes);
                out.flush();
                callback.onWriteFinished(new PageRange[]{PageRange.ALL_PAGES});
            } catch (Exception e) {
                callback.onWriteFailed(e.getMessage());
            } finally {
                try {
                    if (out != null) out.close();
                } catch (Exception ignored) {
                }
            }
        }
    }
}
